### ISSUE TITLE
City selection: spanish version

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-city-selection-scrolly-spanish#1]
## Action Items 

- [x] Fork
- [x] GPT translate components
- [x] Test superflow with Svelte
- [x] Add own google anayltics
- [x] Pull in updates from responsive patch pending Drexel-UHC/salurbal-city-selection-scrolly#3 closing
- [x] Superflow spanish text updates

**Comment by usamabilal** [comment]
Done! added comments in superflow, very minor. lmk if you have any questions

**Comment by ran-codes** [comment]
Mobile updates + superflow text edits made:  

Anyone want to give a final look over before closing the issue and putting into production?

review link: https://mellow-blancmange-4aad09.netlify.app/?review=true

**Comment by usamabilal** [comment]
Minor edits, once those are addressed i think we can close

**Comment by ran-codes** [comment]
- [x] second round of edits
- [x] build + deploy
- [x] review link: https://mellow-blancmange-4aad09.netlify.app/?review=true
- [x] production link: https://drexel-uhc.github.io/salurbal-city-selection-scrolly-spanish/ 

Thanks for the help everyone 🍰 🍰
