### ISSUE TITLE
Superflow bug

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-city-selection-scrolly-spanish#2]
superflow is buggy login right now.

## Action Items

- [x] document bug and send to superflow team
- [x] test/deploy markerio: https://flourishing-khapse-8b17b2.netlify.app/
- [x] wait on Superflow team
- [ ] pending @usamabilal thoughts on markerio: https://flourishing-khapse-8b17b2.netlify.app/

**Comment by ran-codes** [comment]
## Superflow bug sent to superflow

![jZZCYWV](https://github.com/Drexel-UHC/salurbal-city-selection-scrolly-spanish/assets/45013044/2ba5832a-43d2-44a6-8d2b-66c05e99c596)

**Comment by ran-codes** [comment]
@usamabilal I contact superflow. hope it should be resolved today. But here's the markerio version if want ot try it out: https://flourishing-khapse-8b17b2.netlify.app/

**Comment by ran-codes** [comment]
well super flow is working. Note that this was a user-error. we mispsecified the URL for superbase to connect to. Next time double check URL matches between client URL and superflow URL.

**Comment by usamabilal** [comment]
great! commenting on #1 instead
